model = "gpt-5.3-codex"
model_reasoning_effort = "high"
approval_policy = "on-failure"
personality = "pragmatic"

[features]
streamable_shell = true
web_search_request = true

[sandbox_workspace_write]
network_access = true

[projects."${HOME}/Github/"]
trust_level = "trusted"
